name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 👇 Ye step zaroori hai
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci --include=dev
      - run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HR_MANAGE_DASHBOARD }}
          channelId: live
          projectId: hr-manage-dashboard
